# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: CmdLine@2
  inputs:
    script: |
      git checkout master
      git add -- all
      git push https://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@github.com/fergonzalez47/Group-06-Project-HH.git

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
